version: '3'
services:
  dev3:
    container_name: dev3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2203:22"
      - "9993:9000"
      - "8003:80"
    networks: 
       SSID:
          ipv4_address: 172.50.0.4
    hostname: dev3
    volumes:
      - /Users/annika/Documents/SSI-Simulator:/purple
    cap_add:
      -  NET_ADMIN
    command: sudo python3 /opt/internal.py 3 1 10 3 0
    stdin_open: true
    tty: true
              
  dev2:
    container_name: dev2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2202:22"
      - "9992:9000"
      - "8002:80"
    networks: 
       SSID:
          ipv4_address: 172.50.0.3
    hostname: dev2
    volumes:
      - /Users/annika/Documents/SSI-Simulator:/opt/purple
    cap_add:
      -  NET_ADMIN
    command: sudo python3 /opt/internal.py 2 1 10 3 0
    depends_on:
      - dev3
    stdin_open: true
    tty: true
              
  dev1:
    container_name: dev1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2201:22"
      - "9991:9000"
      - "8001:80"
    networks: 
       SSID:
          ipv4_address: 172.50.0.2
    hostname: dev1
    volumes:
      - /Users/annika/Documents/SSI-Simulator:/purple
    cap_add:
      -  NET_ADMIN
    command: sudo python3 /opt/internal.py 1 1 10 3 0
    depends_on:
      - dev2
    stdin_open: true
    tty: true
              
volumes:
    purple:
networks:
    SSID:
        ipam:
            driver: default
            config:
                - subnet: 172.50.0.0/24
                  gateway: 172.50.0.254
