FROM ubuntu

RUN apt update && apt install iproute2 sudo python3 coreutils tcpdump vim tmux git tmuxinator pip docker net-tools -y
RUN apt install netcat ncat socat openssh-server autoconf automake autotools-dev sshpass ptunnel iputils-ping -y
RUN pip install paramiko pexpect 